//
// Edge.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Edge: JSONEncodable {
    public var id: UUID?
    public var head: UUID?
    public var tail: UUID?
    public var _class: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["head"] = self.head?.encodeToJSON()
        nillableDictionary["tail"] = self.tail?.encodeToJSON()
        nillableDictionary["class"] = self._class
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
