//
// InlineResponse2003In.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse2003In: JSONEncodable {
    public var _5f9e769ff6fe4cee02b3b4547200db6b: NodeEdge?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["5f9e769ff6fe4cee02b3b4547200db6b"] = self._5f9e769ff6fe4cee02b3b4547200db6b?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
